### ISSUE TITLE
Lua error in WebLinks modul

### ISSUE THREAD

**Issue by Nihlo** [ScottHamper/chatsuey#8] opened 2017-11-08 20:14 UTC
Hey, thanks a lot for your addons. Get a small error on login though

![](https://user-images.githubusercontent.com/26931653/32410873-5bcd61c2-c1cb-11e7-8174-7cc01be568a7.jpg)

**Comment by ScottHamper** [comment] 2022-09-22 17:23
Closing this issue since it's been nearly five years... Sorry about that!

This error would have been caused by calling the `AddMessage` function on a chat frame without passing in a `text` parameter. ChatSuey never calls the `AddMessage` function itself (sort of - technically it proxies calls to `AddMessage`, but it never initiates a call), and I'm not aware of any situation where the WoW client would call it without a `text` parameter. My guess is that another addon was doing something weird.

**Closed by ScottHamper** 2022-09-22 17:23 UTC
